// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package protobuf.AggregatedSensorReading

object AggregatedSensorReadingProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq.empty
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      protobuf.AggregatedSensorReading.AggregatedSensorReading
    )
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """Ch1BZ2dyZWdhdGVkU2Vuc29yUmVhZGluZy5wcm90bxIIcHJvdG9idWYikwQKF0FnZ3JlZ2F0ZWRTZW5zb3JSZWFkaW5nEikKC
  HNlbnNvcklkGAEgASgFQg3iPwoSCHNlbnNvcklkUghzZW5zb3JJZBJHChJhdmVyYWdlVGVtcGVyYXR1cmUYAiABKAJCF+I/FBISY
  XZlcmFnZVRlbXBlcmF0dXJlUhJhdmVyYWdlVGVtcGVyYXR1cmUSPgoPYXZlcmFnZUh1bWlkaXR5GAMgASgCQhTiPxESD2F2ZXJhZ
  2VIdW1pZGl0eVIPYXZlcmFnZUh1bWlkaXR5EkcKEm1pbmltdW1UZW1wZXJhdHVyZRgEIAEoAkIX4j8UEhJtaW5pbXVtVGVtcGVyY
  XR1cmVSEm1pbmltdW1UZW1wZXJhdHVyZRJHChJtYXhpbXVtVGVtcGVyYXR1cmUYBSABKAJCF+I/FBISbWF4aW11bVRlbXBlcmF0d
  XJlUhJtYXhpbXVtVGVtcGVyYXR1cmUSPgoPbWluaW11bUh1bWlkaXR5GAYgASgCQhTiPxESD21pbmltdW1IdW1pZGl0eVIPbWlua
  W11bUh1bWlkaXR5Ej4KD21heGltdW1IdW1pZGl0eRgHIAEoAkIU4j8REg9tYXhpbXVtSHVtaWRpdHlSD21heGltdW1IdW1pZGl0e
  RIyCgtub09mUmVjb3JkcxgIIAEoA0IQ4j8NEgtub09mUmVjb3Jkc1ILbm9PZlJlY29yZHNiBnByb3RvMw=="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, _root_.scala.Array(
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}